version: "3.1"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    env_file:
      - .env
    environment:
      dbString: ${dbString}
    ports:
      - "80:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    image: mongo:4.0.3
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    
    volumes:
      - ../data/db:/data/db
