version: "3.0"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
